name: Build STM32 Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install ARM Toolchain & Build Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi make cmake

    - name: Configure project with CMake
      run: cmake -Bbuild -DCMAKE_BUILD_TYPE=Release

    - name: Build firmware
      run: cmake --build build

    - name: Copy .hex file to artifact directory
      run: |
        mkdir -p artifacts
        find build -name "*.hex" -exec cp {} artifacts/ \;

    - name: Upload .hex as GitHub Actions artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: firmware-hex
        path: artifacts/*.hex
      



